### ISSUE TITLE
Por favor código nacional, popular y libre

### ISSUE THREAD

**Issue by josx** [peronismo/peronismo.github.io#1]
Hey, ayer un compañero de la cooperativa nos dío el link y varios hicieron el test.
Además como trabajamos con vuejs es más interesante aún para poder reutilizar, ayudar  y/o que otros puedan hacer creaciones.

Estaría bueno si podes compartir como software libre en éste o otro repo, el código fuente sin hacer el build, todo separado como alentar que otros puedan colaborar o reutilizarlos. 

gracias!

**Comment by peronismo** [comment]
Hola Josx. Me pasas alguna forma de contactarte? La verdad soy absolutamente newbie en estas cosas y no se hacer lo que me pedis. De todas formas ya me estoy poniendo a investigar.

**Comment by peronismo** [comment]
Hecho.
Viva Perón carajo.
